def run():
    print("Possible methods to implement a Google Docs competitor:")
    print()
    print("1. Operational Transformation (OT)")
    print("   - Used by Google Docs itself")
    print("   - Transforms concurrent edits so they converge to the same state")
    print("   - Requires a central server to order operations")
    print()
    print("2. Conflict-Free Replicated Data Types (CRDTs)")
    print("   - Peer-to-peer friendly, no central server required")
    print("   - Libraries: Yjs, Automerge, Diamond Types")
    print("   - Each character gets a unique ID for merging without conflicts")
    print()
    print("3. Differential Synchronization")
    print("   - Invented by Neil Fraser (Google)")
    print("   - Exchange diffs between client and server in a sync cycle")
    print("   - Simpler than OT but less granular conflict resolution")
    print()
    print("4. WebSocket + Event Sourcing")
    print("   - Broadcast every keystroke/edit as an event via WebSockets")
    print("   - Store events in an append-only log for replay and undo")
    print("   - Combine with OT or CRDTs for conflict resolution")
    print()
    print("5. Prosemirror / TipTap + Collaboration Backend")
    print("   - Use Prosemirror's collaboration module (OT-based)")
    print("   - TipTap wraps Prosemirror with a friendlier API")
    print("   - Pair with Hocuspocus server for real-time sync")
    print()
    print("6. Build on Existing Protocols")
    print("   - Matrix protocol for decentralized real-time sync")
    print("   - WebRTC for peer-to-peer document editing")
    print("   - Gun.js for decentralized graph-based storage")
